/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author vsvineeth
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Vyakthamalla.setVisible(false);
    }
    public void visible(javax.swing.JLabel label,Boolean value)
    {
     	label.setVisible(value);
    }
    public void changecolor(javax.swing.JLabel label)
    {
    	String name=label.getName();
    	System.out.println("Name : "+name);
    	label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/"+name+"Red.jpg")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ChakkaLogo = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        AdakkukaStart = new javax.swing.JLabel();
        Thudanguka = new javax.swing.JLabel();
        Vyakthamalla = new javax.swing.JLabel();

        AdakkukaStart.setName("AdakkukaStart");
        Thudanguka.setName("Thudanguka");
        
        setBackground(java.awt.Color.white);

        ChakkaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ChakkaLogo.jpg"))); // NOI18N

        Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Name.jpg"))); // NOI18N

        AdakkukaStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AdakkukaStartBlack.jpg"))); // NOI18N

        Thudanguka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ThudangukaBlack.jpg"))); // NOI18N

        Vyakthamalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Vyakthamalla.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ChakkaLogo)
                .addGap(135, 135, 135)
                .addComponent(Name)
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Vyakthamalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Thudanguka)
                .addGap(84, 84, 84)
                .addComponent(AdakkukaStart)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChakkaLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Name)
                        .addGap(123, 123, 123)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Vyakthamalla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdakkukaStart)
                            .addComponent(Thudanguka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    public javax.swing.JLabel AdakkukaStart;
    private javax.swing.JLabel ChakkaLogo;
    private javax.swing.JLabel Name;
    public javax.swing.JLabel Thudanguka;
    public javax.swing.JLabel Vyakthamalla;
    // End of variables declaration                   
}
