/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author vsvineeth
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        Vyakthamalla.setVisible(false);
    }
    
    public void changecolor(javax.swing.JLabel label)
    {
    	String name=label.getName();
    	System.out.println("Name : "+name);
    	label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/"+name+"Red.jpg")));
    }

    public void visible(javax.swing.JLabel label,Boolean value)
    {
     	label.setVisible(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ChakkaLogo = new javax.swing.JLabel();
        NameSmall = new javax.swing.JLabel();
        Vyakthamalla = new javax.swing.JLabel();
        Thiranjedukkuka = new javax.swing.JLabel();
        BusLogo = new javax.swing.JLabel();
        BusTiming = new javax.swing.JLabel();
        Sancharamargam = new javax.swing.JLabel();
        Adakkuka = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Wikipedia = new javax.swing.JLabel();
        WikiLogo = new javax.swing.JLabel();
        News = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        
        BusTiming.setName("BusTiming");
        Adakkuka.setName("Adakkuka");
        Sancharamargam.setName("Sancharamargam");
        News.setName("News");
        Wikipedia.setName("Wikipedia");

        ChakkaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ChakkaLogo.jpg"))); // NOI18N

        NameSmall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NameSmall.jpg"))); // NOI18N

        Vyakthamalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Vyakthamalla.gif"))); // NOI18N

        Thiranjedukkuka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Thiranjedukkuka.jpg"))); // NOI18N

        BusLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Bus.jpg"))); // NOI18N

        BusTiming.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BusTimingBlack.jpg"))); // NOI18N

        Sancharamargam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SancharamargamBlack.jpg"))); // NOI18N

        Adakkuka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AdakkukaBlack.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AtoB.jpg"))); // NOI18N

        Wikipedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WikipediaBlack.jpg"))); // NOI18N

        WikiLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WikipediaLogo.jpg"))); // NOI18N

        News.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NewsBlack.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NewsLogo.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ChakkaLogo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Adakkuka)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Thiranjedukkuka)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(News)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BusLogo)
                                            .addComponent(WikiLogo))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BusTiming)
                                            .addComponent(Sancharamargam)
                                            .addComponent(Wikipedia))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))
                        .addContainerGap(173, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(NameSmall))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Vyakthamalla)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ChakkaLogo)
                .addGap(11, 11, 11)
                .addComponent(NameSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Vyakthamalla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(News)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Adakkuka)
                .addGap(12, 12, 12)
                .addComponent(Thiranjedukkuka)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(Wikipedia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BusLogo)
                            .addComponent(BusTiming, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(Sancharamargam)
                        .addGap(10, 10, 10)
                        .addComponent(WikiLogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    public javax.swing.JLabel Adakkuka;
    private javax.swing.JLabel BusLogo;
    public javax.swing.JLabel BusTiming;
    private javax.swing.JLabel ChakkaLogo;
    private javax.swing.JLabel NameSmall;
    public  javax.swing.JLabel News;
    public javax.swing.JLabel Sancharamargam;
    private javax.swing.JLabel Thiranjedukkuka;
    public javax.swing.JLabel Vyakthamalla;
    private javax.swing.JLabel WikiLogo;
    public javax.swing.JLabel Wikipedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
