/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author vsvineeth
 */
public class NewsChoice extends javax.swing.JPanel {

    /**
     * Creates new form NewsChoice
     */
    public NewsChoice() {
        initComponents();
    }
    
    public void changecolor(javax.swing.JLabel label)
    {
    	String name=label.getName();
    	System.out.println("Name : "+name);
    	label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/"+name+"Red.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoSmall = new javax.swing.JLabel();
        NameSmall = new javax.swing.JLabel();
        Adakkuka = new javax.swing.JLabel();
        Thiranjedukkuka = new javax.swing.JLabel();
        MathrubhumiLogo = new javax.swing.JLabel();
        IndiavisionLogo = new javax.swing.JLabel();
        TheHinduLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MathrubhumiLogo.setName("MathrubhumiLogo");
        IndiavisionLogo.setName("IndiavisionLogo");
        TheHinduLogo.setName("TheHinduLogo");
        Adakkuka.setName("Adakkuka");

        setBackground(java.awt.Color.white);

        LogoSmall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ChakkaLogoSmall.jpg"))); // NOI18N

        NameSmall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NameSmall.jpg"))); // NOI18N

        Adakkuka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AdakkukaBlack.jpg"))); // NOI18N

        Thiranjedukkuka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Thiranjedukkuka.jpg"))); // NOI18N

        MathrubhumiLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MathrubhumiLogoBlack.jpg"))); // NOI18N

        IndiavisionLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/IndiavisionLogoBlack.jpg"))); // NOI18N

        TheHinduLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/TheHinduLogoBlack.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NewsIcon.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NewsIcon.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NewsIcon.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LogoSmall)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Thiranjedukkuka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Adakkuka)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndiavisionLogo)
                                    .addComponent(MathrubhumiLogo))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(NameSmall))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(TheHinduLogo)))
                .addGap(0, 311, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(439, 439, 439)
                    .addComponent(jLabel5)
                    .addContainerGap(877, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoSmall)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Adakkuka)))
                .addGap(50, 50, 50)
                .addComponent(NameSmall)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Thiranjedukkuka)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MathrubhumiLogo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(IndiavisionLogo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel3)))
                        .addGap(114, 114, 114)
                        .addComponent(TheHinduLogo))
                    .addComponent(jLabel6))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(jLabel5)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Adakkuka;
    private javax.swing.JLabel LogoSmall;
    private javax.swing.JLabel NameSmall;
    private javax.swing.JLabel Thiranjedukkuka;
    public javax.swing.JLabel MathrubhumiLogo;
    public javax.swing.JLabel IndiavisionLogo;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel TheHinduLogo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
